# Generated by Django 4.1.7 on 2023-04-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NSLife', '0002_user_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=64)),
                ('datetime', models.DateTimeField()),
                ('score', models.IntegerField(blank=True)),
            ],
        ),
    ]
