# Generated by Django 4.1.7 on 2023-04-13 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NSLife', '0004_exercise_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=64)),
                ('datetime', models.DateTimeField()),
                ('intensity', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mannings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
