# Generated by Django 4.1.7 on 2023-04-13 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NSLife', '0005_manning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manning',
            old_name='datetime',
            new_name='end_datetime',
        ),
        migrations.AddField(
            model_name='manning',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
